### PR TITLE
fix: order for clean up changed

### PR DESCRIPTION
**Pull request by girdharshubham**

### CODE REVIEW

**Review by tusharmath — APPROVED** [review]

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 17.03**

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 17.04**

**Comment by girdharshubham** [comment]
`scalafixSemanticdb.revision` in BuildHelper.scala resolves to 4.4.28 which makes the benchmark build crash. To fix this, `semanticdbVersion` is explicitly set to the latest version that is there on sonatype. i.e. [4.4.30](https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.7/). 

Latest scalafix version: `0.9.32`

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 17.03**

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 17.03**

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 17.03**

**Pull request merged**
