### PR TITLE
Feature: Add mapError to middleware

### LINKED ISSUE #938: Add `mapError` operator in Middleware Domain
**Is your feature request related to a problem? Please describe.**
Currently we don't have a `mapError` operator for MIddleware

**Describe the solution you'd like**

```scala
final def mapError[E1](ee: E => E1): Middleware[R, E1, AIn, BIn, AOut, BOut] = ???
```

### PR DESCRIPTION
**Pull request by beem812**
Aiming to close #938

### CODE REVIEW

**Comment by beem812** [comment]
I see that I missed a change to middleware and will get this refactored to fit the new style.

**Comment by tusharmath** [comment]
You might want to take a pull. The implementation has changed completely :)

**Comment by beem812** [comment]
Yea, I’m working on the update now, having trouble translating it to the new format since it doesn’t seem like I can change the error type inside the middleware apply method.

**Comment by tusharmath** [comment]
@beem812 Yes, you are right. We will also need a `EIn` and `EOut` now and similarly `RIn` and `ROut` also if we want to implement `provide` family of operators.

```scala
trait class Middleware[+RIn, -EIn, +AIn, -BIn, -ROut, +EOut, -AOut, +BOut] { self =>
  def apply(http: Http[RIn, EIn, AIn, BIn]): Http[ROut, EOut, AOut, BOut]
}
```

**Comment by beem812** [comment]
@tusharmath I still have quite a bit of work left but I was wondering if you could check a few of these types I've come up with so far having added an EOut and ROut to the middle ware type. I could be completely off with these and better to know sooner than later: 

```Scala
 final def andThen[RIn1 <: ROut, EIn1 >: EOut, AIn1 <: AOut, BIn1 >: BOut, ROut1, EOut1, AOut1, BOut1](
    other: Middleware[RIn1, EIn1, AIn1, BIn1, ROut1, EOut1, AOut1, BOut1],
  ): Middleware[RIn, EIn, AIn, BIn, ROut1, EOut1, AOut1, BOut1] =
    new Middleware[RIn, EIn, AIn, BIn, ROut1, EOut1, AOut1, BOut1] {
      override def apply(http: Http[RIn, EIn, AIn, BIn]): Http[ROut1, EOut1, AOut1, BOut1] =
        other(self(http))
    }

  /**
   * Applies middleware on Http and returns new Http.
   */
  def apply(http: Http[RIn, EIn, AIn, BIn]): Http[ROut, EOut, AOut, BOut]

  /**
   * Makes the middleware resolve with a constant Middleware
   */
  final def as[BOut0](
    bout: BOut0,
  ): Middleware[RIn, EIn, AIn, BIn, ROut, EOut, AOut, BOut0] =
    self.map(_ => bout)

  /**
   * Combines two middleware that operate on the same input and output types,
   * into one.
   */
  final def combine[R0 <: ROut, E0 >: EOut, A0 >: AIn <: AOut, B0 >: BOut <: BIn](
    other: Middleware[R0, E0, A0, B0, R0, E0, A0, B0],
  ): Middleware[RIn, EIn, A0, B0, R0, E0, A0, B0] =
    self andThen other

  /**
   * Preprocesses the incoming value for the outgoing Http.
   */
  final def contramap[AOut0](f: AOut0 => AOut): Middleware[RIn, EIn, AIn, BIn, ROut, EOut, AOut0, BOut] =
    self.contramapZIO[AOut0](a => UIO(f(a)))

  /**
   * Preprocesses the incoming value using a ZIO, for the outgoing Http.
   */
  final def contramapZIO[AOut0]: Middleware.PartialContraMapZIO[RIn, EIn, AIn, BIn, AOut, BOut, AOut0] =
    new Middleware.PartialContraMapZIO(self)

  /**
   * Delays the production of Http output for the specified duration
   */
  final def delay(duration: Duration): Middleware[RIn with Clock, EIn, AIn, BIn, ROut, EOut, AOut, BOut] =
    self.mapZIO(b => UIO(b).delay(duration))
   ```

**Comment by tusharmath** [comment]
Looks good :)

**Comment by beem812** [comment]
I just pushed the beginnings of the changes but I've been stumped on the typing for flatMap, I can't get it to type check without flipping the type bounds on the RIn and EIn and I'm out of my element on that kind of thing.

**Comment by frekw** [comment]
I've also done some work [here](https://github.com/frekw/zio-http/tree/feat/middleware-tap-both) (only introducing `EIn` and `EOut`). `Middleware.scala` seems to compile but am getting errors from multiple call sites so fairly certain I messed something up along the way, the typespecs get kind of hairy. 😅

**Comment by frekw** [comment]
Sorry for the bad link, here's a better one: https://github.com/frekw/zio-http/compare/main..feat/middleware-tap-both

**Pull request closed without merging**
