### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by guizmaii** [comment]
This is most probably a zio-sbt issue and shouldn't be fixed this way but by updating zio-sbt and re-running the readme generation task

**Comment by ghost** [comment]
> the readme generation task

wow!

Anyways, if you do this fast, the do it your way. Otherwise just merge for now, so the broken links (= sloppy impression) are fixed.

**Comment by guizmaii** [comment]
Your PR breaks CI for the reasons I mentioned

**Comment by ghost** [comment]
> Your PR breaks CI for the reasons I mentioned

You are aware that you break the possibly most basic standard-procedure within OS: fixing a README on github.

You really should free this poor README from the CI/Generator-Tyrany.

Closing.

**Pull request closed without merging**
