### PR TITLE
Serving React SPA with Zio Http

### LINKED ISSUE #2292: Zio-http and Reactjs example project
**Is your feature request related to a problem? Please describe.**
I am new to zio, i want to develop full-stack web app with `zio-http` and `react.js`.
I couldn't figure out how to serve static files after calling `npm run build` in the react.js project.

**Describe the solution you'd like**
It would be nice if zio-http documentation includes an example simple full-stack app with serving files.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Resolves #2292
/claim #2292

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Can't find any reason related to "react" in the GH Actions that have failed.

Happy to update the README if with any specifics that resolve the below 👇🏻
Screenshot 2023-11-22 at 12 53 18 PM

**Comment by vigoo** [comment]
Hello. The problem is that your example is based on `3.0.0-RC2` but since the documentation is compiled with the latest version (and the example should reflect that too). In the latest version (since `3.0.0-RC3`) there is no `Http` type anymore.

So please do the following changes:
- Make `zio-http-react-example` a submodule of the main `build.sbt` like `zio-http-example` is - that way it will depend on the actual version of the repo, not a previous release like now. 
- By this change it will no longer compile (because of the same reasons why the `fullstack-with-ract-apps.md` is not compiling now). You can fix the example easily by using the updated DSL. See for example https://github.com/zio/zio-http/blob/main/zio-http-example/src/main/scala/example/HelloWorldAdvanced.scala#L21-L24
- Once the example subproject compiles you can copy the changes to the markdown as well, and verify if it compiles by doing `sbt docs/mdoc`

**Comment by rishi-raj-jain** [comment]
Commands followed to test that the whole thing works:

```
git clone repo
sbt
```

> in the sbt console
```
reStart
```

Checkout: [http://localhost:8080](http://localhost:8080) & [http://localhost:8080/api/hello](http://localhost:8080/api/hello)

**Comment by rishi-raj-jain** [comment]
https://github.com/zio/zio-http/assets/46300090/8ac85c63-f990-4f03-93fa-8734b17c7229

**Comment by rishi-raj-jain** [comment]
@vigoo 

Thank you for your detailed response! I've added the recording and the code of the same.

**Comment by rishi-raj-jain** [comment]
@vigoo ready for your review

**Comment by rishi-raj-jain** [comment]
@vigoo ready for your review

**Comment by rishi-raj-jain** [comment]
@vigoo @jdegoes ready for your review

**Comment by jdegoes** [comment]
@rishi-raj-jain Can you please look into [this failure](https://github.com/zio/zio-http/actions/runs/7043432782/job/19169199719?pr=2529)?

**Comment by jdegoes** [comment]
@rishi-raj-jain The build is still failing and there are conflicts. Can you please re-open the PR when (1) CI is passing the build, and (2) there are no conflicts? I would like to merge this in but we cannot break CI to do so.

**Pull request closed without merging**
