### PR TITLE
chore: update project plugins

### PR DESCRIPTION
**Pull request by ezhil56x**
## Description
- Last part of `README.md` is auto generated using `zio-sbt-website` not using `index.md`
- This is common on most of the `zio` repos 
- This fix is already done in [https://github.com/zio/zio-sbt/pull/223/](https://github.com/zio/zio-sbt/pull/223/)
- Bumped `zio-sbt-website` version to `0.4.0-alpha.22` which fixes the issue
- This fixes the issue #2576 and broken links in all other repos of `zio`
- If required I can raise a PR for version bump on other repos of `zio`

/claim #2576

### CODE REVIEW

**Comment by ezhil56x** [comment]
@jdegoes @khajavi

Required changes are made. Hope so this PR is ready to merge!

**Comment by khajavi** [comment]
@ezhil56x To make the CI green, please run this sbt command and commit the changes.
https://github.com/zio/zio-http/actions/runs/7556121624/job/20572470305?pr=2618#step:4:69

**Comment by ezhil56x** [comment]
@khajavi Seems to be no changes to commit when I run `sbt docs/generateReadme`


https://github.com/zio/zio-http/assets/103899034/68b43443-1f3d-4f7e-a169-947e95352cf1

**Comment by khajavi** [comment]
> @khajavi Seems to be no changes to commit when I run `sbt docs/generateReadme`
> 
>  2024-01-18.07-24-22.mp4

I did the same and ran `sbt docs/generateReadme` and committed the `README.md` changes.

> * If required I can raise a PR for version bump on other repos of `zio`

I would appreciate it if you could do that!

**Comment by ezhil56x** [comment]
@khajavi Is this ready to merge or require changes to be made?

**Comment by khajavi** [comment]
> @khajavi Is this ready to merge or require changes to be made?

It is ready to be merged.

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@ezhil56x Can you fix conflicts? 🙏

**Comment by ezhil56x** [comment]
> @ezhil56x Can you fix conflicts? 🙏

Yep, will do

**Comment by ezhil56x** [comment]
@jdegoes Fixed the conflicts!

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
