### PR TITLE
Fixing specified dependency and CI badge in README.md

### PR DESCRIPTION
**Pull request by fmarl**
Hello,

just a small fix of the CI badge as well as the dependency in the README.md. This has caused some confusion for me, so I thought I'd fix it. :)

### CODE REVIEW

**Comment by jdegoes** [comment]
cc @khajavi

**Comment by khajavi** [comment]
@fxttr Thanks for your contribution.
The README.md file is auto-generated from `docs/index.md` and some sbt metadata via `docs/generateReadme`.
This work will fail the [Website / Build and Test CI](https://github.com/zio/zio-http/actions/runs/3914217518/jobs/6705629611) workflow.

**Comment by fmarl** [comment]
Ah I see, didn't knew that, sorry.

**Comment by khajavi** [comment]
@fxttr Are you going to complete this PR to fix the proposed issues?

**Pull request closed without merging**
