### PR TITLE
RichTextCodec.describe

### PR DESCRIPTION
**Pull request by gregor-rayman**
Still work in progress. For #1693

### CODE REVIEW

**Comment by jdegoes** [comment]
@gregor-rayman I love where you are going with this.

In order to generate BNF, we would need two things:

1. Labels associated with terms (particularly recursive ones).
2. Handling of cyclic graphs through an identity map.

An example RFC in some variant of BNF:

```
Accept = #( media-range [ accept-params ] )

     media-range    = ( "*/*"
                      / ( type "/" "*" )
                      / ( type "/" subtype )
                      ) *( OWS ";" OWS parameter )
     accept-params  = weight *( accept-ext )
     accept-ext = OWS ";" OWS token [ "=" ( token / quoted-string ) ]
```

This happens to not be recursive but relies heavily on parts being named.

I made a very light implementation that does not handle recursion and does not use an intermediate ADT. Do you have interest in pushing your version forward?

**Comment by gregor-rayman** [comment]
I'd love to pushing this forward. 

Currently the labels are simple numbers, with few exceptions: the main term is called main, some character sets have predefined labels (digits, letters, whitespace, ...).  If the codecs had names, that would for sure help. 

Now I generate the labels only if: 
  * the codecs are used recursively (I had to change `repeat` from `def` to `lazy val` to avoid infinite recursion)
  * the codec is not trivial (e.g. CharIn or literal) and is used multiple times.

To further proceed in this direction, I'd add optional name to a codec. The name would always be used as a label, even for non recursive single usage. This could also help to identify recursively used codes generated dynamically (def vs lazy val - if those are needed anyway), because the `describe` method could treat them as the same codec. (Naming two different codecs the same should be probably considered an error and lead to an invalid description)

**Comment by jdegoes** [comment]
@gregor-rayman That's fantastic news! We could have something extremely impressive, capable of generating fantastic documentation for all HTTP headers, query parameters, etc.

I agree with your step of adding labels. I suggest adding a new subtype of `RichTextCodec` called `Labelled` that stores the label and the codec.

Then we can have:

```scala
sealed trait RichTextCodec[A] {
  ...
  def labeled(name: String): RichTextCodec[A] = ...
  ...
}
```

Maybe with a symbolic operator `??` (often used to attach docs to ADTs in ZIO libraries).

Then you can use a `List[TextCodec[_]]` (???) to keep track of which term you are in as you recurse. 

I think you are on the right track to build an intermediate form that looks like BNF. With the labels, you will then have productions in the grammar that you can use to render in the classic `BINARY_OP = '+' | '-' | ...` form.

If something doesn't have a name, you can use the reference identity of the text codec to identify it, which assumes that people use `lazy val` for recursive codecs (I think that assumption is fine).

Let's try to produce a single `code` block that contains the whole grammar. 

Let me know if you need help!

**Comment by gregor-rayman** [comment]
I am almost finished :)

The cycles as still a bit tricky. Another issue is quoting literals, because now "a|z" can be interpreted as literal "a" or literal "z"; or as literal "a|z". But that will be the second step.

**Comment by gregor-rayman** [comment]
I have created draft PR #1741.

**Pull request closed without merging**
