### PR TITLE
Create SmithyParser.scala

### PR DESCRIPTION
**Pull request by promisingcoder**
Add SmithyParser to convert Smithy models to OpenAPI and then generate endpoints from OpenAPI
/claim #1522 
I am still in the beginning but due to me not knowing what to do next I made the pull request

### CODE REVIEW

**Comment by 987Nabil** [comment]
I don't like this approach. Converting to OpenAPI removes precision in modeling. One reason why smithy exists and is liked is, that it does things different/better than OpenAPI. Reducing it to OpenAPI removes the benefits (for example a better modeling of sum types.) I think we should have dedicated smithy support.

wdyt @jdegoes

**Comment by promisingcoder** [comment]
@jdegoes could you please give me an update on this approach ??

**Comment by promisingcoder** [comment]
@987Nabil 
until now 
when it comes to union types 
there is no problem in the generation from smithy to openapi the problem is in the way that codegen.writefiles generates zio specs from openapi 
I will find a way to pass the right things  to that function so that it generates the required output 
I will detail here in a bit how is this happening

**Comment by promisingcoder** [comment]
and by the way `"EchoUnion": {
                "oneOf": [
                    {
                        "type": "object",
                        "title": "stringMessage",
                        "properties": {
                            "stringMessage": {
                                "type": "string",
                                "pattern": "^[a-zA-Z]+$"
                            }
                        },
                        "required": [
                            "stringMessage"
                        ]
                    },
                    {
                        "type": "object",
                        "title": "intMessage",
                        "properties": {
                            "intMessage": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "intMessage"
                        ]
                    }
                ]
            }`
            ## generated redunant code  from CodeGen.WriteFiles() 
            `package your.base.package.component

import zio.schema._
import zio.schema.annotation._

@noDiscriminator
sealed trait EchoUnion
object EchoUnion {


 implicit val codec: Schema[EchoUnion] = DeriveSchema.gen[EchoUnion]
case class EchoUnion(
 stringMessage: String
)
object EchoUnion {



 implicit val codec: Schema[EchoUnion] = DeriveSchema.gen[EchoUnion]



}
case class EchoUnion(
 intMessage: Double
)
object EchoUnion {



 implicit val codec: Schema[EchoUnion] = DeriveSchema.gen[EchoUnion]



}
         }`

**Comment by promisingcoder** [comment]
> and by the way `"EchoUnion": { "oneOf": [ { "type": "object", "title": "stringMessage", "properties": { "stringMessage": { "type": "string", "pattern": "^[a-zA-Z]+$" } }, "required": [ "stringMessage" ] }, { "type": "object", "title": "intMessage", "properties": { "intMessage": { "type": "number" } }, "required": [ "intMessage" ] } ] }` ## generated redunant code from CodeGen.WriteFiles() `package your.base.package.component
> 
> import zio.schema._ import zio.schema.annotation._
> 
> @noDiscriminator sealed trait EchoUnion object EchoUnion {
> 
> implicit val codec: Schema[EchoUnion] = DeriveSchema.gen[EchoUnion] case class EchoUnion( stringMessage: String ) object EchoUnion {
> 
> implicit val codec: Schema[EchoUnion] = DeriveSchema.gen[EchoUnion]
> 
> } case class EchoUnion( intMessage: Double ) object EchoUnion {
> 
> implicit val codec: Schema[EchoUnion] = DeriveSchema.gen[EchoUnion]
> 
> } }`
2
## I will make sure to fix this If you want @jdegoes @987Nabil

**Comment by jdegoes** [comment]
I don't think we should go through OpenAPI as an intermediate. Too lossy and not what was intented in the original ticket.

**Pull request closed without merging**
