### PR TITLE
Comprehensive documentation  >> Docs rewrite

### PR DESCRIPTION
**Pull request by daveads**
###  Roll out Comprehensive documentation for ZIO HTTP #2198 

Would like to keep experimenting and exploring zio-http to better understand what's going on and constantly update the doc...

*  Introduction ✅ 
*  Concepts 
     * Routing ✅ 
     * Request Handling ✅ 
     * Server ✅ 
     * Client ✅ 
     * Middleware ✅ 
     * Endpoint ✅ 
* Tutorials
     * Your First ZIO HTTP App ✅ 
     * Deploying a ZIO HTTP App
     * Testing Your ZIO HTTP App
* How-to-guides
     * (This should be based off the list of topics at http4k, but should also include ZIO HTTP use cases around Endpoint, middleware, etc.) ✅ 
* Reference
     *  API Docs
     * Server backend
     * Websockets
     * JSON Handling 
     * Metrics
     * Request Logging
     * (etc.)
* Performance ✅ 
* FAQ ✅ 

/claim #2198

### CODE REVIEW

**Comment by daveads** [comment]
hello @jdegoes , could you please start reviewing my pull request? I'd like to know where I can focus on improving.

**Comment by jdegoes** [comment]
@daveads Can you please fix all conflicts?

**Comment by daveads** [comment]
okay...

**Comment by daveads** [comment]
@jdegoes resolved the conflicts, so I guess you can start the review now.

**Comment by jdegoes** [comment]
@daveads Ready to merge this if you can fix conflicts!

**Comment by daveads** [comment]
@jdegoes  fixed

**Comment by daveads** [comment]
I still don't understand why **Website / Build and Test (pull_request)** keeps failing.

**Comment by jdegoes** [comment]
Run `docs` and `mdoc`. They are separate commands.

**Comment by daveads** [comment]
@jdegoes  i keep get an error coming from  **zio-http/src/main/scala/zio/http/codec/RichTextCodec.scala**

**Comment by TomTriple** [comment]
> @jdegoes i keep get an error coming from **zio-http/src/main/scala/zio/http/codec/RichTextCodec.scala**

That should be fixed when https://github.com/zio/zio-http/pull/2439 is merged

**Comment by daveads** [comment]
> Run `docs` and `mdoc`. They are separate commands.

@jdegoes  done this but **Website / Build and Test** keeps failing

**Comment by daveads** [comment]
@jdegoes    _Website / Build and Test (pull_request)_   build successful now, working on some other aspects.

**Comment by adithyaakrishna** [comment]
@daveads Could you please lmk if there is any update on this?

**Comment by daveads** [comment]
@adithyaakrishna what updates are you referring to ?

**Comment by jdegoes** [comment]
@ daveads  Can you update conflicts?

**Comment by daveads** [comment]
alright i will update it. @jdegoes

**Comment by jdegoes** [comment]
@daveads The CI does not pass the build and there are conflicts still. Please re-open if you want us to take another look when all problems have been addressed. 🙏

**Pull request closed without merging**
