### PR TITLE
Added Encode and Decode Tests.

### PR DESCRIPTION
**Pull request by nsc1234**

### CODE REVIEW

**Comment by jdegoes** [comment]
@nsc1234 Good to merge after the CLA is digitally signed! See above for a link to sign the CLA. Both contributors in the PR need to sign the CLA.

**Comment by jdegoes** [comment]
Now @SaadASTheDev must sign the CLA and then the CI build should pass!

**Comment by jdegoes** [comment]
@nsc1234 Everything is passing! Do you want to push more commits to this branch, or do you want me to merge this in, and you can open up a new pull request with a new branch??

**Comment by nsc1234** [comment]
> @nsc1234 Everything is passing! Do you want to push more commits to this branch, or do you want me to merge this in, and you can open up a new pull request with a new branch??

Thank you! Can you please merge this in?

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Thanks for your work, and congratulations on your first OSS contribution!

**Pull request merged**
