### PR TITLE
Documentation or examples for sending websocket messages - Issue#1418

### PR DESCRIPTION
**Pull request by JatinSharma32**
## PR Description
- Added documentation for sending WebSocket messages using @gregor-rayman 's example code
- Added new document in the __Sidebar.js__

## Checks
- [x] sbt Build

```bash
> I am new to Open source, so if you need some improvement in this PR please let me know,
> Always open to feedback 🙂.
```

/claim #1418

### CODE REVIEW

**Comment by vigoo** [comment]
Thanks!

**Comment by JatinSharma32** [comment]
Please check my Latest commit, Fixed those __\<br\>__ tag issues

**Comment by JatinSharma32** [comment]
This time finally, I have removed/modified all possible breaking points for JSX.

**Comment by JatinSharma32** [comment]
please check, I've updated

**Comment by jdegoes** [comment]
@JatinSharma32 I increased the bounty on this. Due to a recent PR merge, the web socket API has been simplified. Can you update this and we can get this merged back in?

**Comment by JatinSharma32** [comment]
Can you refer me to that PR?
Is it this https://github.com/zio/zio-http/pull/2152 ?

**Comment by adamgfraser** [comment]
@JatinSharma32 That's the one!

**Comment by jdegoes** [comment]
@JatinSharma32 Will close this for now, please re-open when you get a chance to fix!

**Pull request closed without merging**
