### PR TITLE
Documentation: Reference Section on Sidebar

### PR DESCRIPTION
**Pull request by khajavi**
Restructured the sidebar to have a reference section

image

### CODE REVIEW

**Comment by daveads** [comment]
@khajavi my pr is already doing this 

https://github.com/zio/zio-http/pull/2780

**Comment by khajavi** [comment]
@daveads No problem! If your work merged before this PR, I'll update this PR to reflect your work and merge only the differences.

**Comment by khajavi** [comment]
@jdegoes It is ready for review!

**Comment by daveads** [comment]
> @daveads No problem! If your work merged before this PR, I'll update this PR to reflect your work and merge only the differences.

sure

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
