### PR TITLE
Resolve conflict with zio-logging lib

### PR DESCRIPTION
**Pull request by changzhiwin**
Changes:
1, using `package zio.http.logging` for zio-http-logging project

Due to the same package name with [zio-logging](https://github.com/zio/zio-logging)

### CODE REVIEW

**Comment by adamgfraser** [comment]
I think this should be a unary operator on `Server`.

**Comment by changzhiwin** [comment]
> I think this should be a unary operator on `Server`.

@adamgfraser any good case? 
I checked `http4s` using method for this purpose.
And I don't know any unary operator suitable for this case, please give a hint.

**Comment by adamgfraser** [comment]
```scala
trait Server {
  def port(port: Int): Server
}
```

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@changzhiwin The CI build is failing, can you please look into it?

**Comment by jdegoes** [comment]
I merged the other PR that changes the package names, because it was passing. Please re-open this PR when the build is passing and conflicts are merged if you'd like to push through the other changes! Thank you.

**Comment by changzhiwin** [comment]
@jdegoes I think use `zio/http/logging` dir better than `zio/logging`.

**Pull request closed without merging**
