### PR TITLE
Schema based query codecs including validation (#2937)

### LINKED ISSUE #2937: Endpoint: add query codec validation for max/min length and regex
OpenAPI supports such limitations and it also seems fitting for our API.

### PR DESCRIPTION
**Pull request by 987Nabil**
fixes #2937
/claim #2937

### CODE REVIEW

**Comment by 987Nabil** [comment]
@jdegoes PR was already big enough. But there is some follow up work to do.
1. Integrate the validation information in OpenAPI. I started with this for the bodies already. The PR is blocked by a zio-schema bug. But now queries needs it too. I will open a new issue.
2. I modified the `TextBinaryCodec`, so it works for Records with exactly one field. This is used in query codec, but only works if the user gives the query param name. To improve this, we should add that one can define a case class and the query codec looks for query params that fit all field names `HttpCodec.query[Params]` where `case class Params(perPage: Int, page: Int)` to read two query params

**Comment by jdegoes** [comment]
> To improve this, we should add that one can define a case class and the query codec looks for query params that fit all field names HttpCodec.query[Params] where case class Params(perPage: Int, page: Int) to read two query params

It would be nice to get this one done as part of this PR, if possible.

**Review by jdegoes — APPROVED** [review]

**Comment by 987Nabil** [comment]
I just realized, this fixes #2945 as well
/claim #2945

**Comment by anqit** [comment]
It'd be great if user-facing changes like this included doc updates as well

**Comment by 987Nabil** [comment]
@anqit we will check and update all docs before the final 3.0 release.
Also, there are no API changes.
Take a look at this for API changes including adjusted docs. https://github.com/zio/zio-http/pull/3000/files#diff-af8fd425043c6947f3e6b86e9b2fb5fdefa737968e9b63458fe6ceb8938ce5ce

**Pull request merged**
