### PR TITLE
Simplify/Optimize HandlerTree for Constant Routes

### PR DESCRIPTION
**Pull request by kitlangton**
This builds on top of https://github.com/zio/zio-http/pull/1537

### CODE REVIEW

**Comment by jdegoes** [comment]
@kitlangton Looks like a fantastic start!! Can you fix CI, and also post before/after benchmarks?

**Comment by kitlangton** [comment]
Yup! :) CI is being a pest. Looks like I’ll need a few more “fix compilation” commits

**Comment by kitlangton** [comment]
```scala
// Original
//
// [info] ApiBenchmark.benchmarkBroadTapirHttp4s      thrpt    2  115.028          ops/s
// [info] ApiBenchmark.benchmarkBroadZioApi           thrpt    2  751.619          ops/s
// [info] ApiBenchmark.benchmarkBroadZioCollect       thrpt    2  126.598          ops/s
//
// [info] ApiBenchmark.benchmarkDeepPathTapirHttp4s   thrpt    2   65.697          ops/s
// [info] ApiBenchmark.benchmarkDeepPathZioApi        thrpt    2  565.441          ops/s
// [info] ApiBenchmark.benchmarkDeepPathZioCollect    thrpt    2  956.824          ops/s
//
// [info] ApiBenchmark.benchmarkSmallDataTapirHttp4s  thrpt    2   92.525          ops/s
// [info] ApiBenchmark.benchmarkSmallDataZioApi       thrpt    2  277.247          ops/s
// [info] ApiBenchmark.benchmarkSmallDataZioCollect   thrpt    2  703.899          ops/s
//
// After Branch optimization
//
// [info] ApiBenchmark.benchmarkBroadTapirHttp4s      thrpt    2  118.398          ops/s
// [info] ApiBenchmark.benchmarkBroadZioApi           thrpt    2  979.155          ops/s (up from 751)
// [info] ApiBenchmark.benchmarkBroadZioCollect       thrpt    2  122.202          ops/s
//
// [info] ApiBenchmark.benchmarkDeepPathTapirHttp4s   thrpt    2   65.647          ops/s
// [info] ApiBenchmark.benchmarkDeepPathZioApi        thrpt    2  563.393          ops/s
// [info] ApiBenchmark.benchmarkDeepPathZioCollect    thrpt    2  977.179          ops/s
//
// [info] ApiBenchmark.benchmarkSmallDataTapirHttp4s  thrpt    2   91.951          ops/s
// [info] ApiBenchmark.benchmarkSmallDataZioApi       thrpt    2  264.240          ops/s
// [info] ApiBenchmark.benchmarkSmallDataZioCollect   thrpt    2  698.570          ops/s
```

Here are the results for the difference between looking up constant paths in a map vs. hunting through a list of them. It looks like it earned us around +200 ops.

I tried out some other micro-optimizations for fun and also to help build my intuition for what makes a dent. Some of those included:

- Making the Chunk of results that we're building into an Array
- Pre-optimizing all Handlers into APIServers, removing the `Memoization`, and moving the logic that happens after `lookup` into its body.

But lo and behold, the code got uglier and there wasn't much of a bump. Maybe ~10/20 ops? But it didn't feel worth sacrificing the readability for such a small (potentially random) gain.

I would think we could get this to about match the `collectZIO` API in simple cases. I'm not sure of the culprit. Perhaps it's the `Constructor` logic? But anyway, the good news is that the `API` performance pulls pretty far ahead of everything in a relatively small realistic example (just 15 or so semi-nested endpoints).

**Comment by kitlangton** [comment]
Added an additional optimization that had a nice effect: Only encoding the `Output` into a `Body` if it's not `Unit` has sped up a couple of cases quite significantly. 

```scala
// After `hasBody` check
//
// [info] ApiBenchmark.benchmarkBroadTapirHttp4s      thrpt    2   113.092          ops/s
// [info] ApiBenchmark.benchmarkBroadZioApi           thrpt    2  1745.498          ops/s (from 751)
// [info] ApiBenchmark.benchmarkBroadZioCollect       thrpt    2   125.484          ops/s
//
// [info] ApiBenchmark.benchmarkDeepPathTapirHttp4s   thrpt    2    66.033          ops/s
// [info] ApiBenchmark.benchmarkDeepPathZioApi        thrpt    2   781.366          ops/s (from 563)
// [info] ApiBenchmark.benchmarkDeepPathZioCollect    thrpt    2   944.260          ops/s
//
// [info] ApiBenchmark.benchmarkSmallDataTapirHttp4s  thrpt    2    87.859          ops/s
// [info] ApiBenchmark.benchmarkSmallDataZioApi       thrpt    2   267.333          ops/s (the same because it encodes)
// [info] ApiBenchmark.benchmarkSmallDataZioCollect   thrpt    2   701.566          ops/s
```

Obviously, many APIs _will_ have some kind of body. But it's good to know that's the cause of some delay. It would appear that using `Schema` to decode into `Json` might be a good target for optimization, as the `smallDataCollect` benchmark uses `zip-json` directly. I'll switch that over to doing the same and see if they even out.

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
❤️  Excellent work!

**Pull request merged**
