### PR TITLE
New Response model

### PR DESCRIPTION
**Pull request by hbibel**

### CODE REVIEW

**Comment by Grryum** [comment]
partially closes #2305 (№2)

**Comment by hbibel** [comment]
@jdegoes @adamgfraser Changes are good to go from @Grryum and my side. Can you PTAL?

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@hbibel Looks fantastic! Good to merge when the conflicts are fixed. Can you please take a look? 🙏

**Comment by hbibel** [comment]
@jdegoes Conflicts are fixed. `WebsocketSpec` is currently failing, but I saw it failing on `main` as well, so I presume it's to be expected at the moment?

**Pull request merged**
