### PR TITLE
Server inbound handler performance

### PR DESCRIPTION
**Pull request by jaspervz**

### CODE REVIEW

**Comment by jdegoes** [comment]
@jaspervz Is this built on @fokot's PR or are they independent??

**Comment by jaspervz** [comment]
@jdegoes The work of @fokot's PR is included in this one

**Comment by jdegoes** [comment]
@jaspervz Can you post before / after `jmh` benchmarks? At this point we'd be testing mostly the benchmark, I believe, on whether it was carefully designed enough to pick up these optimizations.

**Comment by jaspervz** [comment]
@jdegoes 
benchmark:

before:
ServerInboundHandlerBenchmark.benchmarkApp  thrpt   25  12643.711 ± 308.766  ops/s

after:
ServerInboundHandlerBenchmark.benchmarkApp  thrpt   25  13077.685 ± 330.450  ops/s

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@jaspervz Thanks for your work on this! 🙏

**Pull request merged**
