### PR TITLE
#2305  refactor response class 

### PR DESCRIPTION
**Pull request by escafl0wne**
#2305 Refactor response class

### CODE REVIEW

**Comment by jdegoes** [comment]
There is overlap with #2348

**Comment by escafl0wne** [comment]
> There is overlap with #2348

Sorry for that, shall i close the request?

**Comment by jdegoes** [comment]
@escafl0wne It would be great to work together on a single PR! Are you available to do that?

**Comment by escafl0wne** [comment]
> @escafl0wne It would be great to work together on a single PR! Are you available to do that?

@jdegoes certainly.

**Comment by escafl0wne** [comment]
> @escafl0wne It would be great to work together on a single PR! Are you available to do that?

@jdegoes silly request but would you mind just have a look into the commit and let me know if the code is worth anything? just for my reassurance .

**Comment by hbibel** [comment]
> @jdegoes silly request but would you mind just have a look into the commit and let me know if the code is worth anything? just for my reassurance .

The code looks great and is similar to what @grryum and I had for some time. However we went further and removed `frozen` and `socketApp` as well.

Also note that in general you don't have to implement `hashCode` and `toString` for Scala case classes.

**Comment by jdegoes** [comment]
@escafl0wne I think this was the right direction but was superceded and subsumed by @hbibel and @Grryum's work. Thank you for your work on this!

**Pull request closed without merging**
