### PR TITLE
Fixing interruption in client

### LINKED ISSUE #1863: Client Request Interruption Not Working as Expected
**Describe the bug**
I have a ZIO HTTP client that connects to a ZIO HTTP server where the server handler sleeps for 10 seconds.  If the client has a timeout of a couple seconds or after a couple seconds interrupts the request, I'd expect the server handler's `onExit` to get a `Failure` as this is what happens when a request is made from curl and cancelled before it is completed.  However, the server handler instead succeeds normally.

**To Reproduce**
See: https://github.com/jamesward/zio-http-client-interrupt
Run the server & client and observe that the timeout request and the interrupted client request do not cause the server handler to produce failures.

**Expected behaviour**
Interrupting a client request should cause a failure on the server handler (I think but maybe I'm doing it wrong).

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #1863 

Based on @jamesward 's PR (https://github.com/zio/zio-http/pull/1893) but I rewrote it as several things changed since then.

### CODE REVIEW

**Comment by jamesward** [comment]
Glad to see progress on this, with tests!  For reference, here are related issues/PRs:
https://github.com/zio/zio-http/pull/1893
https://github.com/zio/zio-http/issues/1863

**Review by jdegoes — APPROVED** [review]

**Comment by vigoo** [comment]
@jdegoes It's failing on CI but I could not reproduce it locally yet. Can be a real issue though so I'll continue investigating. 
We can ignore the test and merge it as it's definitely already better than before, or just keep it open until the remaining issue is fixed.

**Comment by jdegoes** [comment]
Unfortunately if I merge, the CI will be broken. Best to just disable the test if we think it's not that serious and can be fixed later.

**Comment by vigoo** [comment]
Yes that’s what I meant but cannot commit it until next weekOn 2023. Feb 1., at 10:06, John A. De Goes ***@***.***> wrote:﻿
Unfortunately if I merge, the CI will be broken. Best to just disable the test if we think it's not that serious and can be fixed later.

**Review by adamgfraser — APPROVED** [review]

**Comment by jamesward** [comment]
I've tested this change in my [Easy Racer ZIO app](https://github.com/jamesward/easyracer/tree/main/scala-zio) and it is working great!

**Comment by vigoo** [comment]
> I've tested this change in my [Easy Racer ZIO app](https://github.com/jamesward/easyracer/tree/main/scala-zio) and it is working great!

That's good to hear! I'm just trying to fix some edge case that only happens on GitHub CI. Hopefully we can merge it soon.

**Comment by vigoo** [comment]
Continued in https://github.com/zio/zio-http/pull/1994

**Pull request closed without merging**
