### PR TITLE
Fix: Handle SSL failures

### LINKED ISSUE #653: Request not resolved on exceptions
**Describe the bug**
Request is not resolved on exceptions

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to SSLSpec
2. Run the ignored test, 
3. it will be timed out because the promise is not resolved on exceptions in ClientInboundHandler

**Expected behavior**
Request should fail with the exception

### PR DESCRIPTION
**Pull request by dinojohn**
fixes #653

### CODE REVIEW

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 431224.84**

**Review by tusharmath — APPROVED** [review]

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 432370.46**

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 430425.47**

**Comment by kitlangton** [comment]
Oh, nice! Would this possibly fix the failure on #645?

**Comment by dinojohn** [comment]
No this will fix the ignored test : `fail with SSLHandshakeException when client doesn't have the server certificate`

**Pull request merged**
