### PR TITLE
fix: broken link in readme

### LINKED ISSUE #2865: circularity in docs
the link on the front git page
Learn more on the [ZIO Http homepage](https://github.com/zio/zio-http)!

is just redirected back to the same place. Where should we learn more?

### PR DESCRIPTION
**Pull request by ezhil56x**
Closes #2865
/claim #2865

### CODE REVIEW

**Comment by ezhil56x** [comment]
@jdegoes 
Can I get a review on this?
Thanks!

**Comment by jdegoes** [comment]
This does not pass the build. Please re-open when build fixed. 🙏

**Comment by ezhil56x** [comment]
@jdegoes 
Build is breaking due to `ContentTypeSpec` referenced in [https://github.com/zio/zio-http/issues/2885](https://github.com/zio/zio-http/issues/2885). I think the fix for this issue works.

**Comment by ezhil56x** [comment]
@jdegoes 
I think as the README.md is generated using `sbt generateReadme`, the idle solution would be to update the `BuildHelper.scala` with the link and use `sbt generateReadme` to generate readme rather than updating the README.md directly

**Comment by ezhil56x** [comment]
> Build is breaking due to `ContentTypeSpec` referenced in #2885. I think the fix for this issue works.

@jdegoes
Can I get a review on this?
Thanks!

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Can you resolve conflicts?

**Comment by ezhil56x** [comment]
@jdegoes Resolved conflicts, a tip would be highly appreciated
Thanks!

**Comment by ezhil56x** [comment]
@jdegoes I think this can be merged! Resolved conflicts

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
