### PR TITLE
Allow appending query parameters in path, and fix grouping of Combiner types

### PR DESCRIPTION
**Pull request by afsalthaj**

### CODE REVIEW

**Comment by jdegoes** [comment]
@afsalthaj Benchmarks failing, can you take a look?

**Comment by afsalthaj** [comment]
@jdegoes  The benchmark job always failed whenever I raised a PR against zio-http.

https://github.com/zio/zio-http/pull/2181#issuecomment-1544296258

**Comment by afsalthaj** [comment]
The reason is quite hard for me to debug, and definitely not a performance regression.

image

**Comment by jdegoes** [comment]
@scottweaver Can you assist tracking down this issue?

**Pull request merged**
