### PR TITLE
Move requestLogging Middleware to API

### PR DESCRIPTION
**Pull request by BalduinLandolt**

### CODE REVIEW

**Comment by BalduinLandolt** [comment]
@irinaschubert here is the PR draft

**Comment by jdegoes** [comment]
@BalduinLandolt It's very difficult to do this one in the new middleware. I might suggest taking an easier ticket that doesn't require altering any of the declarative middleware machinery!

**Comment by jdegoes** [comment]
I will close this for now because it is not super clear on how to do this one. Please re-open if you have ideas about implementing it (but it is not a simple ticket).

**Comment by BalduinLandolt** [comment]
No problem! I came to the same conclusion (see my comment in #1689). I suppose it would require an input HttpCodec that gives access to the entire Request object.... but that's beyond my skill and time availability - for now :)

**Pull request closed without merging**
