### PR TITLE
Enable Client connection pooling by default

### LINKED ISSUE #2149: Enable Client connection pooling by default
Currently the default client in `zio-http` does not use connection pooling by default. We should consider enabling that by default. Most users would benefit from the increased performance, while not having to set up the connection pool by themselves.

### PR DESCRIPTION
**Pull request by ccerbusca**
closes #2149

/claim #2149

### CODE REVIEW

**Review by vigoo — APPROVED** [review]

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
This may be hanging CI, but I don't understand why.

**Comment by vigoo** [comment]
No, some tests are really hanging - reproducible

**Comment by ccerbusca** [comment]
@jdegoes i disabled the client connection pool for that particular test suite. It seems the tests hang at some point when trying to send a new request. Might be an issue with the connection pool? Would merit it's own ticket for further investigation

**Comment by ccerbusca** [comment]
Weird, just in case I ran the tests locally and they did not hang, but still seem to hang on the pipeline

**Pull request merged**
