### PR TITLE
Body content type

### PR DESCRIPTION
**Pull request by eyalfa**
refactor body to have `contentType` instead of separate `media-type` and `boundary`

### CODE REVIEW

**Comment by eyalfa** [comment]
CC: @987Nabil

**Comment by eyalfa** [comment]
@987Nabil did u get to have a look at this?

**Comment by 987Nabil** [comment]
@eyalfa this is not a viable solution. Because you use the a header data type. Bodies have no headers

**Comment by eyalfa** [comment]
> @eyalfa this is not a viable solution. Because you use the a header data type. Bodies have no headers

but I'm not using it as a header, not trying to suggest bodies have headers, they just (usually) have a content type.
information wise this is exactly what's needed in order to describe's a body's content, do u want to introduce a new data type just for that? it'd require converting back and forth with content type header any way

**Comment by 987Nabil** [comment]
I would still prefer that I think. Having a data type that is clearly bound to a header used at a place that is not a header feels wrong.

**Comment by eyalfa** [comment]
@987Nabil I've introduced a Body specific ContentType class

**Comment by eyalfa** [comment]
> @987Nabil I've introduced a Body specific ContentType class

@987Nabil  ☝️

**Review by 987Nabil — APPROVED** [review]

**Pull request merged**
