### PR TITLE
Upgrade to ZIO 2

### PR DESCRIPTION
**Pull request by kitlangton**
@adamgfraser and I worked on upgrading to the RC of ZIO 2. Obviously, you may not want to merge this directly into master 😄 and perhaps would like to open up a new branch instead. Either way, just opening a PR for now for discussion (and CI!).

🥳

### CODE REVIEW

**Comment by kitlangton** [comment]
Interesting. The `SSLSpec` passes locally.

**Comment by tusharmath** [comment]
Thanks @kitlangton! I have created a separate branch `main-zio-2` which we will keep updating with `main`. Trying to figure out why the build is failing.

**Comment by kitlangton** [comment]
INCREDIBLE!!!!!
CleanShot 2021-12-16 at 09 07 58@2x

**Comment by kitlangton** [comment]
Getting weird timeouts on these client SSL specs :'( 
Will take a closer look this next week.

**Comment by adamgfraser** [comment]
@tusharmath All tests are passing now. Looks like there is an issue with the benchmarks, not sure what is going on there.

It looked like in a couple of the SSL tests there was an issue where the channel could get closed before the fiber forked in `HttpRuntime#unsafeRun` completed execution. We addressed by implementing an `unsafeRunUninterruptible` operator that doesn't interrupt the fiber when the channel is closed but would be good to understand why that is occurring and if that is expected behavior.

Also blocked on STTP for the tests now. I wonder if there is a way to test with our own implementation instead?

**Comment by tusharmath** [comment]
Hey @adamgfraser this looks great! Apologies for the conflicts, the main is moving fast. 


- I think the ssl tests are a bit flaky I guess we missed adding the flaky annotation in `main` #654 
- Benchmarks don't run on forked pull requests #619 
- STTP will need to be used until we close #650

**Pull request closed without merging**
