### PR TITLE
Hide all Netty-specific details from packages (as much as possible)

### PR DESCRIPTION
**Pull request by zarinfam**

### CODE REVIEW

**Comment by vigoo** [comment]
We should not hide `NettyConfig` and the layer variants that require it, that is intended to be the public interface for customizing some netty-specific parameters.

**Comment by zarinfam** [comment]
> We should not hide `NettyConfig` and the layer variants that require it, that is intended to be the public interface for customizing some netty-specific parameters.

@jdegoes What is your opinion?

**Comment by jdegoes** [comment]
@zarinfam  As per @vigoo's request, let's leave that one public. 

Can you fix conflicts and run `fmt`, `doc`, and `mdoc` locally to resolve any CI issues?

I'd love to get this merged in for RC3.

**Comment by jdegoes** [comment]
@zarinfam I am going to close this as it as bit-rotted, but feel free to re-open if you have a chance to wrap up this (much-desired) contribution. Thank you!

**Pull request closed without merging**
