### PR TITLE
Improve dx for ZClient

### PR DESCRIPTION
**Pull request by 987Nabil**
- don't append trailing slash for empty pathSuffixes
- add no params method for get/head/delete

### CODE REVIEW

**Review by jdegoes — CHANGES_REQUESTED** [review]
Superb! Can you add a couple tests to make sure no one accidentally breaks the features you added?

**Comment by 987Nabil** [comment]
Sure!

**Comment by 987Nabil** [comment]
@jdegoes I added this now in the client impl., but I actually think it might be better to have this as the general behaviour of `URL`. Wdyt? This would be a breaking change.

**Comment by jdegoes** [comment]
Yes, please push it into URL with tests. 🙏

**Comment by 987Nabil** [comment]
@jdegoes After taking a look at this again, I think it correct as is.
Having a call like `Client.url(...).get("")`adding a trailing slash is unexpected and with the current master state unavoidable.
But, `url / ""` adding a trailing slash seems reasonable, because that is what you wrote in the DSL. And if you want to ensure that there is no trailing slash, you have `URL#dropTrailingSlash`.
So I think this PR is good to go (at least from my side)

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
