### PR TITLE
added all htmx attributes

### PR DESCRIPTION
**Pull request by THM068**
This PR is to add htmx attributes to the zio http. This will enable users to create interactive application using the backend.
You will need to pull the htmx javascript to make the attributes functional.

### CODE REVIEW

**Comment by guersam** [comment]
This update introduces htmx attributes for every user who imports `zio.http.template._`, even when htmx is not used.

I believe it would be more appropriate to use `zio.http.template.htmx`, ideally in a separate (sub)project, to provide enhanced convenience for htmx usage.

**Comment by jdegoes** [comment]
@THM068 I think it makes sense to put into a separate project but can live inside this repo if you like (`zio-http-htmx`?). What do you think?

**Comment by THM068** [comment]
> @THM068 I think it makes sense to put into a separate project but can live inside this repo if you like (`zio-http-htmx`?). What do you think?

Make sense, I will do that

**Comment by jdegoes** [comment]
@THM068 I will close for now, please re-open when it's in a separate submodule of this repository, linked into root project. Thanks for your work on this!

**Pull request closed without merging**
