### PR TITLE
AddHeader* part done

### LINKED ISSUE #1701: Middleware Rewrites - add/set/remove Headers
Part of #1689 

- [x] `addHeader` - parameters: `(header: Header)`
- [ ] `addHeader` - parameters: `(name: CharSequence, value: CharSequence)`
- [x] `addHeaders` - parameters: `(headers: Headers)`
- [ ] `removeHeader` - parameters: `(name: String)`
- [ ] `removeHeaders` - parameters: `(headers: List[String])`
- [ ] `setHeaders` - parameters: `(headers: Headers)`

### PR DESCRIPTION
**Pull request by vder**
heres the partial solution for first 3 middlewares but im not sure how to remove and set headers
resolves #1701

### CODE REVIEW

**Comment by jdegoes** [comment]
Currently there is no way to remove a header in the new middleware machinery. I'd skip the removal methods for now.

Please run `fmt` to fix errors like [this one](https://github.com/zio/zio-http/actions/runs/3343401391/jobs/5541916280#step:6:55). Thank you!

**Comment by vder** [comment]
I've one more doubt regarding this code. I've added test where I add  header to the request with already defined headers and the original headers where replaced. is that expected behavior?

**Comment by jdegoes** [comment]
`addHeaders` will only add headers to the `Response`.  If the response already contains headers, then possibly they will be replaced. I think we should probably fix that by modifying `Response.Patch` appropriately.

**Comment by jdegoes** [comment]
@vder Build failed, can you look into it?

**Comment by jdegoes** [comment]
There are a couple conflicts in the imports section. Can you please resolve? Thank you!

**Comment by devsprint** [comment]
Closed in favor of #1847

**Pull request closed without merging**
