### PR TITLE
Add clearer instructions for making a simple HTTPS server for testing

### LINKED ISSUE #2221: SSL example needs crt and key file creation instructions
The example has a link on this line:

https://github.com/zio/zio-http/blob/1e1be6950475987bd43049bc121e24a0176952d1/docs/examples/basic/https-server.md?plain=1#L23

to instructions for creating certificate. But the instructions do not create a crt and key file. They produce a java keystore and cert file. And there is something about importing, which should not be necessary.

Attempting to follow those instructions and find other internet resources to fill in the missing steps to produce a crt and key file, and follow the example for configuration of ZIO HTTP have resulted in non-working server.

This is the error:

```
timestamp=2023-05-30T12:50:13.689708Z level=WARN thread=#zio-fiber-81 message="Fatal exception in Netty" cause="Exception in thread "zio-fiber-" io.netty.handler.codec.DecoderException: java.lang.NullPointerException: keyCertChain
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
        at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
        at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
        at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.lang.NullPointerException: keyCertChain
                at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39)
                at io.netty.util.internal.ObjectUtil.checkNonEmpty(ObjectUtil.java:211)
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:436)
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:422)
                at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:345)
                at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:84)
                at zio.http.netty.server.SSLUtil$.sslConfigToSslContext(ServerSSLDecoder.scala:76)
                at zio.http.netty.server.ServerSSLDecoder.decode(ServerSSLDecoder.scala:86)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
                at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
                at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
                at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:833)"
May 30, 2023 5:50:13 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: keyCertChain
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)
        at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
        at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
        at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: keyCertChain
        at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39)
        at io.netty.util.internal.ObjectUtil.checkNonEmpty(ObjectUtil.java:211)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:436)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:422)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:345)
        at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:84)
        at zio.http.netty.server.SSLUtil$.sslConfigToSslContext(ServerSSLDecoder.scala:76)
        at zio.http.netty.server.ServerSSLDecoder.decode(ServerSSLDecoder.scala:86)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        ... 16 more
```

I've tried a technique I used elsewhere using openssl command:

```
openssl req -x509 -out server.crt -keyout server.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

and a combination of keytool and openssl to start in a similar way to the referenced medium article but end up with crt and key files:

```
keytool -genkeypair -keyalg RSA -alias server -keystore server.jks -storepass 123456 -dname CN=localhost
keytool -importkeystore -srckeystore server.jks -srcstorepass 123456 -destkeystore server.p12 -srcstoretype jks -deststoretype pkcs12 -deststorepass 123456
openssl pkcs12 -in server.p12 -passin pass:123456 -out server.pem -passout pass:123456
openssl x509 -outform der -in server.pem -passin pass:123456 -out server.crt
openssl rsa -in server.pem -passin pass:123456 -out server.key
```

(This option generates a binary crt file which is different from what the pure openssl one does.)

### PR DESCRIPTION
**Pull request by abcpro1**
closes #2221

<br>

Add clear instructions on how to generate a self-signed TLS certificate, and how to use it to make a simple HTTPS server.

<br>

/claim #2221

### CODE REVIEW

**Comment by gnp** [comment]
This looks like the same technique I put in the issue itself.

When I used this technique and then tried to invoke the ZIO HTTP app via HTTPS using `curl`, the curl command hung and the error I put in the issue itself was logged in the running ZIO app.

I was only able to avoid the hang by testing with a command like `curl -k https://localhost:8080/ping` but I don't think a correctly functioning ZIO HTTP App with a correct (self-signed) certificate should cause `curl` (without the `-k` argument) to hang. That plus the log makes me thing more is required for self-signed SSL to work with ZIO HTTP.

**Comment by abcpro1** [comment]
@gnp the output that you had posted in the issue #2221 shows that the certificate had a bad format or was not loaded.

If you carefully follow the updated instructions, everything should work fine. Just make sure to have the `server.key` and `server.crt` files inside the `src/main/resources` directory.

This is the output from my machine:

```shell
$ curl https://localhost:8090/text -v
*   Trying 127.0.0.1:8090...
* Connected to localhost (127.0.0.1) port 8090 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self-signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

```shell
$ curl https://localhost:8090/text -v --insecure

*   Trying 127.0.0.1:8090...
* Connected to localhost (127.0.0.1) port 8090 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=example.com; OU=?; O=?; L=?; ST=?; C=??
*  start date: Jun 17 10:13:10 2023 GMT
*  expire date: Jun 16 10:13:10 2024 GMT
*  issuer: CN=example.com; OU=?; O=?; L=?; ST=?; C=??
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* using HTTP/1.1
> GET /text HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/8.0.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 200 OK
< content-type: text/plain
< content-length: 12
<
* Connection #0 to host localhost left intact
Hello World!
```

**Comment by jdegoes** [comment]
Can you also add documentation to the microsite that covers similar content? It's great to have it inside the source code and even better to have it on the website.

@gnp Can you confirm the instructions work correctly?

**Comment by abcpro1** [comment]
@jdegoes this file itself is actually part of the microsite https://zio.dev/zio-http/examples/basic/https-server. Or do you have a specific suggestion?

**Comment by gnp** [comment]
Hi. Thanks @abcpro1. I have used your proposed `openssl` command verbatim in my test project and unlike my previous experience `curl` did not hang, even though ZIO HTTP did log warnings about HTTPS handshake problems.

Concern: This recommends running the `openssl` command and putting the resulting _server.crt_ and _server.key_ files in _src/main/resources_ which seems like a really bad idea because of high potential that secrets get checked into source control and/or built into jars. In my case, I first added those files to _.gitignore_, but its a real risk. Ideally, we would have progressive advice. For example:

  * Quick start -- you can use `SSLConfig.generate(behaviour = SSLConfig.HttpBehaviour.Accept)` which will automatically generate what is needed at runtime. But, beware you will have to have clients ignore validations (for example with `-k` aregument to `curl`).
  * Initial preparation for generated SSL configuration -- you can use `openssl` command to generate a self-signed certificate _.crt_ and _.key_ file that you store in _src/main/resources_. But, be careful to not check them in (list them in _.gitignore_ for example).
  * Real development, and other environment (including PROD) deployment -- ??? what is the recommendation ??? surely not building into the jar file by putting in _src/main/resources_? How would we have local development use the same technique we'd want to use in deployed application to get the two files?

@jdegoes -- The suggested `openssl` command worked well enough for me that I've followed the proposed advice in my zio-quickstart-https example here: https://github.com/gnp/zio-quickstart-https/commit/416a6385db37e326e3c53875fbe8a16254beb818. How would you like to proceed?

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
