### PR TITLE
Created doc string interpolation for Endpoint documentation

### PR DESCRIPTION
**Pull request by ayusham001**

### CODE REVIEW

**Comment by ayusham001** [comment]
@987Nabil 
Please review my PR
Let me know if I can make any other improvements.

**Comment by 987Nabil** [comment]
@ayusham001 this has nothing to do with this ticket. It is not about documentation. But about creating a string interpolator

**Comment by ayusham001** [comment]
@987Nabil 
I have to add add a feature of string interpolator?

**Comment by 987Nabil** [comment]
Yes

**Pull request closed without merging**
