### PR TITLE
refactor tests to use assertTrue

### LINKED ISSUE #735: Improve assertions in test cases
**Is your feature request related to a problem? Please describe.**
We could simplify assertions with `assertTrue`

**Describe the solution you'd like**
We could simplify assertions with `assertTrue`. An example of that can be found in DomSpec.scala.

**Describe alternatives you've considered**
None

### PR DESCRIPTION
**Pull request by geoffjohn11**
Addressing https://github.com/dream11/zio-http/issues/735

Is this the correct idea?

Closes #735

### CODE REVIEW

**Comment by tusharmath** [comment]
@geoffjohn11 Yes this is perfect.

**Comment by tusharmath** [comment]
I think original intent of the issue was that all the test should be migrated to this style of assertions :)

Correct me if I am wrong, @girdharshubham

**Comment by girdharshubham** [comment]
> Reference in
> I think original intent of the issue was that all the test should be migrated to this style of assertions :)
> 
> Correct me if I am wrong, @girdharshubham

Yes @tusharmath 
That's what was finalized as an improvement.

**Comment by geoffjohn11** [comment]
> > Reference in
> > I think original intent of the issue was that all the test should be migrated to this style of assertions :)
> > Correct me if I am wrong, @girdharshubham
> 
> Yes @tusharmath That's what was finalized as an improvement.

Could you point out the tests I missed?  I thought I found all the assertions that asserted on Boolean.

**Comment by girdharshubham** [comment]
> > > Reference in
> > > I think original intent of the issue was that all the test should be migrated to this style of assertions :)
> > > Correct me if I am wrong, @girdharshubham
> > 
> > 
> > Yes @tusharmath That's what was finalized as an improvement.
> 
> Could you point out the tests I missed? I thought I found all the assertions that asserted on Boolean.

These are some files which. you can start with, there are other specs that can be replaced as well:
 - EndpointSpec
 - HtmlSpec
 - CookieSpec
 - EncodeClientParamsSpec
 - GetBodyAsStringSpec


Let me know if you need more info. Also, If you are active on discord, we could run it together on the `coffee-machine` voice channel.

**Comment by geoffjohn11** [comment]
> > > > Reference in
> > > > I think original intent of the issue was that all the test should be migrated to this style of assertions :)
> > > > Correct me if I am wrong, @girdharshubham
> > > 
> > > 
> > > Yes @tusharmath That's what was finalized as an improvement.
> > 
> > 
> > Could you point out the tests I missed? I thought I found all the assertions that asserted on Boolean.
> 
> These are some files which. you can start with, there are other specs that can be replaced as well:
> 
>     * EndpointSpec
> 
>     * HtmlSpec
> 
>     * CookieSpec
> 
>     * EncodeClientParamsSpec
> 
>     * GetBodyAsStringSpec
> 
> 
> Let me know if you need more info. Also, If you are active on discord, we could run it together on the `coffee-machine` voice channel.

Thanks for pointing out these tests, sorry I missed them.  My bad!

**Comment by tusharmath** [comment]
@geoffjohn11 Could you please take a pull once :)

**Comment by geoffjohn11** [comment]
> @geoffjohn11 Could you please take a pull once :)

pulled changes from main, please let me know if this pr needs any other changes.  Thanks!

**Comment by tusharmath** [comment]
Conflicts. Sorry about that. I think as soon as you are done, I will merge it next time.

**Comment by girdharshubham** [comment]
Hi @geoffjohn11 
Are you still working on it?

Let us know if there's anything that you need help with.

**Comment by geoffjohn11** [comment]
> Hi @geoffjohn11 Are you still working on it?
> 
> Let us know if there's anything that you need help with.

@girdharshubham I'll try to push the changes with the merge conflicts fixed soon!

**Comment by geoffjohn11** [comment]
@tusharmath @girdharshubham Merge conflicts should be fixed.

**Comment by tusharmath** [comment]
Need to run scalafmt

**Comment by amitksingh1490** [comment]
@geoffjohn11 can you rebase it once more I will merge it right away. Sorry for the conflicts

**Comment by geoffjohn11** [comment]
@amitksingh1490 should be rebased

**Comment by amitksingh1490** [comment]
Formatting broken please run fmt and push the changes

**Comment by amitksingh1490** [comment]
please merge this https://github.com/geoffjohn11/zio-http/pull/1/files and this is good to go

**Comment by geoffjohn11** [comment]
@amitksingh1490 How does this look now?  I think the formatting should be good.

**Comment by tusharmath** [comment]
Apparently there is a split within the team between assert and assertTrue.

Will close this for now. Thanks for the contribution 🙏

**Pull request closed without merging**
