### PR TITLE
Update sbt to 1.5.6

### PR DESCRIPTION
**Pull request by amitksingh1490**
Updates [org.scala-sbt:sbt](https://github.com/sbt/sbt) from 1.5.5 to 1.5.6.
[GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.5.6) - [Version Diff](https://github.com/sbt/sbt/compare/v1.5.5...v1.5.6)

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/d1f07c467137b817ebd4e48817e784f04abee1de/docs/repo-specific-configuration.md) file.

Have a fantastic day writing Scala!

<details>
<summary>Files still referring to the old version number</summary>

The following files still refer to the old version number (1.5.5).
You might want to review and update them manually.
```
docs/website/package-lock.json
```
</details>
<details>
<summary>Ignore future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "org.scala-sbt", artifactId = "sbt" } ]
```
</details>

labels: library-update, early-semver-patch, semver-spec-patch, old-version-remains

### CODE REVIEW

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 431792.21**

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 435072.26**

**Review by girdharshubham — APPROVED** [review]

**Comment by girdharshubham** [comment]
going to re-raise this PR for automerge

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 403485.84**

**Pull request merged**
